=== anna274/web-app/src/main/resources/XSDValidator.xsd
<?xml version="1.0"?>
<schema>
    <element name="hospitals">
        <element name="hospital">
            <complexType>
                <attribute name="name" type="string" use="required"/>
                <element name="department">
                    <complexType>
                        <attribute name="name" type="string" use="required"/>
                        <attribute name="phone" type="string" use="optional"/>
                        <element name="ward">
                            <complexType>
                                <attribute name="number" type="integer" use="required"/>
                                <attribute name="doctor" type="string" use="required"/>
                                <attribute name="placesNumber" type="integer" default="6"/>
                                <element name="patient">
                                    <attribute name="name" type="string" use="required"/>
                                    <attribute name="age" type="integer" use="required"/>
                                    <attribute name="covidStatus" type="string" use="required"/>
                                    <attribute name="insuranceNumber" type="string" use="optional"/>
                                </element>
                            </complexType>
                        </element>
                    </complexType>
                </element>
            </complexType>
        </element>
    </element>
</schema>

=== anna274/web-app/src/main/resources/hospital.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hospitals
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="XSDValidator.xsd">
    <hospital name="Mount Sinai">
        <department name="surgical" phone="32798">
            <ward number="1" doctor="Ivanov" placesNumber="6">
                <patient name="Ivanov-1" age="45" insuranceNumber="234785" diagnosis="broken arm" covidStatus="healthy"/>
                <patient name="Ivanov-2" age="36" diagnosis="broken arm" covidStatus="recovered"/>
                <patient name="Ivanov-3" age="24" insuranceNumber="234785" diagnosis="broken arm" covidStatus="healthy"/>
            </ward>
            <ward number="2" doctor="Sidorov" placesNumber="3">
                <patient name="Sidorov-1" age="45" insuranceNumber="234785" diagnosis="broken arm" covidStatus="sick"/>
                <patient name="Sidorov-2" age="36" diagnosis="broken arm" covidStatus="sick no sypmtoms"/>
            </ward>
        </department>
        <department name="neurological" phone="32748">
            <ward number="1" doctor="Belov" placesNumber="5">
                <patient name="Belov-1" age="45" insuranceNumber="234785" diagnosis="stroke" covidStatus="healthy"/>
                <patient name="Belov-2" age="36" insuranceNumber="234785" diagnosis="migraine" covidStatus="recovered"/>
                <patient name="Belov-3" age="24" diagnosis="migraine" covidStatus="recovered"/>
                <patient name="Belov-4" age="36" diagnosis="stroke" covidStatus="recovered"/>
                <patient name="Belov-5" age="24" diagnosis="migraine" covidStatus="healthy"/>
            </ward>
            <ward number="2" doctor="Sidorov" placesNumber="3">
                <patient name="Sidorov-1" age="45" insuranceNumber="234785" diagnosis="stroke" covidStatus="first level contact"/>
                <patient name="Sidorov-2" age="36" diagnosis="migraine" covidStatus="first level contact"/>
            </ward>
        </department>
    </hospital>
</hospitals>
